# Generated by Django 6.1 on 2026-08-17 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinturon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('orden', models.PositiveIntegerField(help_text='Posición en la progresión: 1=blanco, 2=amarillo, ...', unique=True)),
                ('color_hex', models.CharField(default='#FFFFFF', help_text='Color del cinturón, ej. #FFEB3B', max_length=7)),
                ('sesiones_requeridas', models.PositiveIntegerField(default=0, help_text='Sesiones mínimas para optar a este cinturón')),
            ],
            options={
                'verbose_name': 'Cinturón',
                'verbose_name_plural': 'Cinturones',
                'ordering': ['orden'],
            },
        ),
        migrations.CreateModel(
            name='Practicante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('alumno', 'Alumno'), ('sensei', 'Sensei')], default='alumno', max_length=10)),
                ('fecha_ingreso', models.DateField(auto_now_add=True)),
                ('cinturon_actual', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='practicante', to='entrenamiento.cinturon')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='practicante', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Promocion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now_add=True)),
                ('cinturon_desde', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='promociones_desde', to='entrenamiento.cinturon')),
                ('cinturon_hasta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='promociones_hasta', to='entrenamiento.cinturon')),
                ('otorgada_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promociones_otorgadas', to='entrenamiento.practicante')),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promociones', to='entrenamiento.practicante')),
            ],
            options={
                'verbose_name': 'Promoción',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Sesion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('duracion_min', models.PositiveIntegerField(help_text='Duración en minutos')),
                ('dojo', models.CharField(blank=True, max_length=100)),
                ('notas', models.TextField(blank=True)),
                ('practicante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sesiones', to='entrenamiento.practicante')),
            ],
            options={
                'verbose_name': 'Sesión',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presente', models.BooleanField(default=True)),
                ('registrada_por', models.ForeignKey(help_text='Instructor que registró la asistencia', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asistencias_registradas', to='entrenamiento.practicante')),
                ('sesion', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia', to='entrenamiento.sesion')),
            ],
        ),
        migrations.CreateModel(
            name='Tecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150, unique=True)),
                ('categoria', models.CharField(choices=[('kihon', 'Kihon'), ('kata', 'Kata'), ('kumite', 'Kumite'), ('ido_geiko', 'Ido Geiko')], max_length=10)),
                ('cinturon_minimo', models.ForeignKey(help_text='Cinturón a partir del cual se practica esta técnica', on_delete=django.db.models.deletion.PROTECT, related_name='tecnicas', to='entrenamiento.cinturon')),
            ],
            options={
                'verbose_name': 'Técnica',
                'ordering': ['categoria', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='sesion',
            name='tecnicas',
            field=models.ManyToManyField(blank=True, related_name='sesiones', to='entrenamiento.tecnica'),
        ),
    ]
