# Generated by Django 6.1 on 2026-08-17 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sesion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Sesión', 'verbose_name_plural': 'Sesiones'},
        ),
    ]
