# Generated by Django 6.1 on 2026-08-17 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0002_alter_sesion_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promocion',
            options={'ordering': ['-fecha'], 'verbose_name': 'Promoción', 'verbose_name_plural': 'Promociones'},
        ),
    ]
