# Generated by Django 6.1 on 2026-08-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0003_alter_promocion_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tecnica',
            name='categoria',
            field=models.CharField(choices=[('kihon', 'Kihon'), ('kata', 'Kata'), ('kumite', 'Kumite'), ('ido_geiko', 'Ido Geiko'), ('dachi', 'Dachi'), ('tsuki', 'Tsuki'), ('uchi', 'Uchi'), ('uke', 'Uke'), ('geri', 'Geri')], max_length=10),
        ),
    ]
