# Generated by Django 6.1 on 2026-08-25 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0005_cinturon_puede_crear_tecnicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinturon',
            name='puede_crear_tecnicas',
        ),
        migrations.RemoveField(
            model_name='cinturon',
            name='puede_promover',
        ),
        migrations.AddField(
            model_name='cinturon',
            name='otorga_autoridad',
            field=models.BooleanField(default=False, help_text='Si es True, quien tenga este cinturón puede promover y crear técnicas (negro, danes...)'),
        ),
    ]
