# Generated by Django 6.1 on 2026-08-25 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0006_remove_cinturon_puede_crear_tecnicas_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cinturon',
            name='otorga_autoridad',
        ),
        migrations.AddField(
            model_name='cinturon',
            name='puede_crear_tecnicas',
            field=models.BooleanField(default=False, help_text='Si es True, quien tenga este cinturón puede crear técnicas (café y superiores)'),
        ),
        migrations.AddField(
            model_name='cinturon',
            name='puede_promover',
            field=models.BooleanField(default=True, help_text='Si es True, quien tenga este cinturón puede promover a otros (negro y danes)'),
        ),
    ]
