# Generated by Django 6.1 on 2026-09-07 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrenamiento', '0007_remove_cinturon_otorga_autoridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cinturon',
            name='puede_promover',
            field=models.BooleanField(default=False, help_text='Si es True, quien tenga este cinturón puede promover a otros (negro y danes)'),
        ),
    ]
